server:
  port: 8088

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/bdtg?characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: gdyakj
    password: gdyakj
    #url: jdbc:mysql://127.0.0.1:3306/testdb?characterEncoding=UTF-8&serverTimezone=GMT%2B8
    #username: root
    #password: 1234
    type: com.alibaba.druid.pool.DruidDataSource

    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    filters: stat
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

  thymeleaf:
    enabled: true
    encoding: utf-8
    prefix: classpath:/templates/
    cache: false
    mode: HTML
    suffix: .html

mybatis:
  mapper-locations: classpath:/mapper/*.xml
